/**
 * Validates test code generated by pilot-ai before execution.
 * Blocks dangerous APIs that could be used for code injection or system access.
 */

/** Patterns that are not allowed in test code. */
const BLOCKED_PATTERNS: Array<{ pattern: RegExp; reason: string }> = [
  // Dangerous globals
  { pattern: /\beval\s*\(/, reason: 'eval() is not allowed' },
  { pattern: /\bFunction\s*\(/, reason: 'Function() constructor is not allowed' },

  // Node.js built-in modules that should not be used in tests
  { pattern: /\brequire\s*\(/, reason: 'require() is not allowed — use ES imports only' },
  { pattern: /(?:from|import)\s+['"](?:node:)?child_process['"]/, reason: 'child_process module is not allowed' },
  { pattern: /(?:from|import)\s+['"](?:node:)?fs['"]/, reason: 'fs module is not allowed' },
  { pattern: /(?:from|import)\s+['"](?:node:)?fs\/promises['"]/, reason: 'fs/promises module is not allowed' },
  { pattern: /(?:from|import)\s+['"](?:node:)?net['"]/, reason: 'net module is not allowed' },
  { pattern: /(?:from|import)\s+['"](?:node:)?dgram['"]/, reason: 'dgram module is not allowed' },
  { pattern: /(?:from|import)\s+['"](?:node:)?cluster['"]/, reason: 'cluster module is not allowed' },
  { pattern: /(?:from|import)\s+['"](?:node:)?worker_threads['"]/, reason: 'worker_threads module is not allowed' },
  { pattern: /(?:from|import)\s+['"](?:node:)?vm['"]/, reason: 'vm module is not allowed' },

  // Process manipulation
  { pattern: /\bprocess\.exit\s*\(/, reason: 'process.exit() is not allowed' },
  { pattern: /\bprocess\.kill\s*\(/, reason: 'process.kill() is not allowed' },
  { pattern: /\bprocess\.env\b/, reason: 'process.env access is not allowed in test code' },

  // Dynamic imports of non-playwright modules (broad catch)
  { pattern: /\bimport\s*\(\s*['"](?!@playwright)/, reason: 'Dynamic imports are restricted to @playwright modules' },
];

/** Modules allowed in import/from statements. */
const ALLOWED_IMPORT_PREFIXES = [
  '@playwright/test',
  '@playwright/',
  'playwright',
];

/** Pattern to extract static import module specifiers. */
const IMPORT_PATTERN = /(?:import\s+.*?\s+from|import)\s+['"]([^'"]+)['"]/g;

export interface ValidationResult {
  valid: boolean;
  errors: string[];
}

/**
 * Validate test code for dangerous patterns before writing to temp file.
 * Returns a ValidationResult with `valid: false` and error messages if violations found.
 */
export function validateTestCode(code: string): ValidationResult {
  const errors: string[] = [];

  // Check blocked patterns
  for (const { pattern, reason } of BLOCKED_PATTERNS) {
    if (pattern.test(code)) {
      errors.push(reason);
    }
  }

  // Check that all imports are from allowed modules
  let match: RegExpExecArray | null;
  const importPattern = new RegExp(IMPORT_PATTERN.source, 'g');
  while ((match = importPattern.exec(code)) !== null) {
    const moduleName = match[1];
    const isAllowed = ALLOWED_IMPORT_PREFIXES.some((prefix) =>
      moduleName.startsWith(prefix),
    );
    if (!isAllowed) {
      errors.push(`Import of "${moduleName}" is not allowed — only @playwright modules are permitted`);
    }
  }

  return {
    valid: errors.length === 0,
    errors,
  };
}
